export let products = [
    {
      id: 1,
      title: "Cubrebocas",
      price: 50,
      description: "Cubrebocas desechables de alta protección.",
      imageUrl: "url_de_imagen", 
      stock: 100,
      category: "cubrebocas",
    },
    {
      id: 2,
      title: "Guantes de Nitrilo",
      price: 300,
      description: "Guantes de nitrilo resistentes para procedimientos médicos.",
      imageUrl: "url_de_imagen", 
      stock: 50,
      category: "guantes",
    },
    {
      id: 3,
      title: "Batas Quirúrgicas",
      price: 200,
      description: "Batas quirúrgicas desechables.",
      imageUrl: "url_de_imagen", 
      stock: 30,
      category: "batas",
    },
    {
      id: 4,
      title: "Kits de Blanqueamiento",
      price: 1500,
      description: "Kits para blanqueamiento dental profesional.",
      imageUrl: "https://res.cloudinary.com/dcerhiol0/image/upload/v1728523385/SP_Logo_Final_tdqkqs.png", 
      stock: 20,
      category: "ortodoncia",
    },
    {
      id: 5,
      title: "Cepillo Interdental",
      price: 100,
      description: "Cepillo interdental para limpieza de espacios entre dientes.",
      imageUrl: "url_de_imagen", 
      stock: 75,
      category: "ortodoncia",
    },
    {
      id: 6,
      title: "Brackets Metálicos",
      price: 2000,
      description: "Brackets metálicos de alta durabilidad.",
      imageUrl: "ortodoncia", 
      stock: 40,
      category: "brackets",
    },
    {
      id: 7,
      title: "Brackets Cerámicos",
      price: 2500,
      description: "Brackets estéticos de cerámica.",
      imageUrl: "url_de_imagen", 
      stock: 35,
      category: "ortodoncia",
    },
    {
      id: 8,
      title: "Alambre de Acero",
      price: 500,
      description: "Alambres de acero para ortodoncia.",
      imageUrl: "url_de_imagen", 
      stock: 60,
      category: "ortodoncia",
    },
    {
      id: 9,
      title: "Bandas Molares",
      price: 150,
      description: "Bandas para molar de ortodoncia.",
      imageUrl: "url_de_imagen", 
      stock: 80,
      category: "ortodoncia",
    },
  ];
  